### ISSUE TITLE
Revision Sprint

### ISSUE THREAD

**Issue by sbuc** [dbosk/crocus#161]
by default 1 day per task, daily scrum at 9.30, plus ad-hoc discussions

Week 1:

- [x] Monday: centralized identity, appendix with identity?, collect/review issues from git and last sprint, merge submittable [branch: submittable-pets; ] 
- [x] Tuesday: adversary model #164
- [x] Wednesday: complexity of protocol #171 #172 #166 
- [x] Thursday: db
- [x] Friday: discussion #163, #165 (plus in security analysis, verifiability) formalization (get input from Cristina) 

- [ ] go through master(-backup) and see what needs to be pulled into submittable (master)
- [ ] go through reviews
- [x] (functional encryption: "TF-resistance, no matter the computation")

Week
Monday: 
- [x] plan
Tuesday: 
- [x] edits from Friday's discussion,
- [x] low-hanging issues
Wednesday: 
- [x] other issues, 
- [ ] revise performance section
Thursday:
- [ ] summary of changes text 
- [x] proof read, polish
Friday:
emergency buffer
